version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - doxygen
    - graphviz

sphinx:
  configuration: doc/sphinx/source/conf.py

python:
  install:
  - requirements: doc/sphinx/requirements.txt
