version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - doxygen

python:
  install:
  - requirements: doc/sphinx/requirements.txt

sphinx:
  configuration: doc/sphinx/conf.py
